Feature/seminar7 구현중 , , ,
IN-SOPT-ANDROID/junseo-kim pull request #5
Opened 2022-12-10 12:15 UTC by giovannijunseokim

2022-12-24 07:41 UTC, murjune requested changes
너무 늦게 코드리뷰하는 감이 있지만.. 고생하셨습니다!!

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/data/remote/api/AuthInterceptor.kt
> +            .build()
오옹?? header를 추가한 이유가 있을까요?? 그냥 연습해보려구 한건가??

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/data/remote/model/MusicDto.kt
> +//)
불필요한 주석 삭제해주세요~

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/login/view/LoginActivity.kt
> +        intent.putExtra("userId", userId)
상수화해주세용

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/GalleryFragment.kt
> +class GalleryFragment(private val userId: Int) : Fragment() {
Fragment 생성자를 오버로딩해서 Fragment 객체를 만들면 안됩니다!!

 `메모리가 부족하다거나 화면이 회전`되는 등의 이벤트가 발생할시에  Activity가 재생성되게되고, Fragment도 재생성하게 됩니다. (아시다시피 Fragment는 Activity의 Lifecycle에 종속적이기 때문이죠 ㅎ ㅎ)  
그런데, Fragment 재생성될 때 `Fragment의 기본 생성자`를 통해 Fragment 객체를 생성하게됩니다.   
> 위와 같은 GalleryFragment와 같이 생성자를 오버로딩해서 GalleryFragment 인스턴스를 만들게 되면 앱 Crash가 나겠죠?  
한 번, GalleyFragment에서 화면 회전을 시켜보시죠.. ㅋㅋㅋ

따라서, Fragment로 data를 전달할 때, Bundle을 사용하거나 ActivityViewModel을 사용하는 것이 일반적입니다.
만약, 위와 같이 Fragment 생성자 오버로딩을 통해 data를 전달하고 싶다면, custom `FramentFactory`를 만들어서 사용해야합니다.

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/GalleryFragment.kt
> +        }
함수화 해주세연~ ㅋㅋㅋ

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/HomeFragment.kt
> +    private var userList: List<ResponseGetUserDto.User>? = listOf()
```suggestion
    private var userList: List<ResponseGetUserDto.User> = listOf()
```
`?`연산자를 넣어준 이유가 있을까여?

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/MusicFragment.kt
> +    private val title = "다음 팟장은 누구일까"
김준서? ㅋㅋㅋㅋ

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/MusicFragment.kt
> +                binding.rvMusics.smoothScrollToPosition(0)
함수화~

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/MusicFragment.kt
> +                binding.rvMusics.smoothScrollToPosition(0)
흐음.. Activity의 ViewBinding객체에 접근하는 것이 과연 맞는걸까요??  
그리고, binding 변수는 항상 private이여야 합니다

2022-12-24 07:41 UTC, murjune commented on app/src/main/java/org/sopt/sample/presentation/main/view/MainActivity.kt
>          }
함수화!!

2022-12-26 08:13 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/data/remote/api/AuthInterceptor.kt
> +            .build()
마자마자 세미나 자료에 있길래 그냥 연습해보려구 ㅋㅋㅋㅎ

2022-12-26 08:13 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/data/remote/model/MusicDto.kt
> +//)
넵 !

2022-12-26 08:14 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/MusicFragment.kt
> +    private val title = "다음 팟장은 누구일까"
ㅋㅋㅋㅋㅋ에바지~

2022-12-26 08:17 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/login/view/LoginActivity.kt
> +        intent.putExtra("userId", userId)
어 이거 상수화 해놓고 안썼네,,,

2022-12-26 09:27 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/GalleryFragment.kt
> +class GalleryFragment(private val userId: Int) : Fragment() {
아하 이해했다..... 메인 액티비티에서  프래그먼트 전환을 할 땐 userId를 넣어주니까 상관이 없지만, 만약 화면 회전등에 의해 프래그먼트를 재구성할 땐 userId를 줄 수 없어서 앱 Crash가 나겠구나 !! 덕분에 하나 알아가 땡큐 ~~~

2022-12-26 09:31 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/GalleryFragment.kt
> +        }
ㅋㅋㅋ깜빡했다... 넵!

2022-12-26 09:38 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/HomeFragment.kt
> +    private var userList: List<ResponseGetUserDto.User>? = listOf()
만약 서버에서 널값이 올까봐,,였는데 그럴 일 없겠네?? 애초에 DTO도 널러블하지 않게 작성했구. 수정할게 !!

2022-12-27 10:08 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/fragment/MusicFragment.kt
> +                binding.rvMusics.smoothScrollToPosition(0)
다른 컴퓨터에 마우스 꽂지 않기 ㅋㅋ

2022-12-27 10:31 UTC, giovannijunseokim commented
1차 코드리뷰 반영 완료 !

2022-12-30 08:09 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/sample/presentation/main/view/MainActivity.kt
>          }
네네넵!

2024-09-07 07:11 UTC, closed without merging